import Axios from 'axios';

export const FETCH_PEXEL_IMAGE_START = "FETCH_PEXEL_IMAGE_START";
export const FETCH_PEXEL_IMAGE_FAIL = "FETCH_PEXEL_IMAGE_FAIL";
export const FETCH_PEXEL_IMAGE_SUCCESS = "FETCH_PEXEL_IMAGE_SUCCESS";